### PR TITLE
Update PT-BR translation

### PR DESCRIPTION
**Pull request by marciozomb13**
Little fixes and improvements.

### CODE REVIEW

**Comment by DrAcHe981** [comment]
This pull is from the master branch, right? 

So this are old string, please take a look at the 1.5 branch for the newest files!

**Comment by marciozomb13** [comment]
OK, thanks.

Marcio de Andrade 

Enviado por TypeApp

Em 18 de jul de 2016 10:25, em 10:25, Shadow notifications@github.com escreveu:

**Comment by marciozomb13** [comment]
I requested to work on POEditor but no answer yet, then I'm here. Thanks!

Marcio de Andrade 

Enviado por TypeApp

Em 18 de jul de 2016 10:25, em 10:25, Shadow notifications@github.com escreveu:

**Comment by DrAcHe981** [comment]
I got no email, but I will check right now on poeditor...

**Comment by marciozomb13** [comment]
Translation is done! On POEditor
Thanks.

Marcio de Andrade 

Enviado por TypeApp

Em 18 de jul de 2016 14:54, em 14:54, Shadow notifications@github.com escreveu:

**Pull request closed without merging**
